begin;
create extension if not exists pgtap with schema extensions;
select plan(12);
select ok(not has_table_privilege('anon', 'public.users', 'SELECT'), 'anon cannot read users');
select ok(not has_table_privilege('authenticated', 'public.users', 'UPDATE'), 'authenticated cannot change users');
select ok(not has_table_privilege('anon', 'public.app_sessions', 'SELECT'), 'anon cannot read sessions');
select ok(not has_table_privilege('authenticated', 'public.app_sessions', 'INSERT'), 'authenticated cannot create sessions');
select ok(not has_function_privilege('anon', 'public.create_telegram_session(bigint,text,text)', 'EXECUTE'), 'anon cannot issue sessions');
select ok(not has_function_privilege('authenticated', 'public.get_app_session(text)', 'EXECUTE'), 'authenticated cannot resolve sessions');
select ok(not has_function_privilege('anon', 'public.revoke_app_session(text)', 'EXECUTE'), 'anon cannot revoke sessions');
select ok((select bool_and(relrowsecurity) from pg_class where oid in ('public.users'::regclass, 'public.app_sessions'::regclass)), 'RLS enabled on both tables');
set local role service_role;
select public.create_telegram_session(123456789012, 'Первое имя', repeat('a',64));
select public.create_telegram_session(123456789012, 'Новое имя', repeat('b',64));
reset role;
select is((select count(*) from public.users where telegram_id=123456789012), 1::bigint, 'repeated login keeps one user');
select is(public.get_app_session(repeat('b',64))->'user'->>'displayName', 'Новое имя', 'session resolves current user');
update public.app_sessions set expires_at=now()-interval '1 second' where token_hash=repeat('a',64);
select is(public.get_app_session(repeat('a',64)), null::jsonb, 'expired session rejected');
set local role service_role;
select public.revoke_app_session(repeat('b',64));
reset role;
select is(public.get_app_session(repeat('b',64)), null::jsonb, 'revoked session rejected');
select * from finish();
rollback;
